#!/usr/bin/env python3
# SPDX-License-Identifier: CERN-OHL-S-2.0
from __future__ import annotations

import argparse
from pathlib import Path
import sys

import pcbnew

from prepare_autoroute import (
    add_cc_resistor,
    assign_missing_functional_nets,
    ensure_net,
    footprint,
    replace_usb_connector,
    set_pad_net,
)


def remove_if_present(board: pcbnew.BOARD, reference: str) -> None:
    item = board.FindFootprintByReference(reference)
    if item is not None:
        board.Remove(item)


def normalize(input_path: Path, output_path: Path) -> None:
    board = pcbnew.LoadBoard(str(input_path))
    if board is None:
        raise RuntimeError(f"cannot load {input_path}")

    replace_usb_connector(board)

    for reference in ("R538", "R539"):
        remove_if_present(board, reference)
    add_cc_resistor(board, "R538", "USB_CC1", 181.0, 70.5)
    add_cc_resistor(board, "R539", "USB_CC2", 184.0, 70.5)

    assign_missing_functional_nets(board)

    # VCM divider high side is the 3V3A rail; avoid a one-end pseudo-net.
    set_pad_net(board, "R529", "1", "3V3A")

    # Local isolated return is deliberately the same continuous local ground net.
    set_pad_net(board, "J11", "2", "AGND")

    # Cable shield is not a subject-contact node; tie only connector shields together.
    set_pad_net(board, "J10", "4", "SHIELD")

    # Ensure all remaining legacy DGND/ISO_GND pad assignments collapse to AGND.
    agnd = ensure_net(board, "AGND")
    for item in board.GetFootprints():
        for pad in item.Pads():
            if pad.GetNetname() in {"DGND", "ISO_GND"}:
                pad.SetNet(agnd)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    pcbnew.SaveBoard(str(output_path), board)

    # Keep all four inner copper declarations as KiCad signal layers until
    # finalized plane/zones are generated by the routing flow.
    text = output_path.read_text(encoding="utf-8")
    text = text.replace('(1 "In1.Cu" power)', '(1 "In1.Cu" signal)')
    text = text.replace('(2 "In2.Cu" power)', '(2 "In2.Cu" signal)')
    output_path.write_text(text, encoding="utf-8")

    print(
        {
            "output": str(output_path),
            "footprints": len(list(board.GetFootprints())),
            "R538": footprint(board, "R538").GetValue(),
            "R539": footprint(board, "R539").GetValue(),
        }
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()
    normalize(Path(args.input), Path(args.output))
    return 0


if __name__ == "__main__":
    sys.exit(main())
